== Advertencia Preliminar

En nuestro  _Primer Libro de Latín_ footnote:[_Primer Libro de Latín_. Barcelona, 1941. Bosch, casa editorial.]
intentamos ofrecer una solución a las especiales
dificultades que la enseñanza de esta lengua ofrece en el primer curso del bachillerato,
dificultades procedentes ante todo del escaso desarrollo intelectual de los alumnos.
Nos propusimos allí, dar del latín una idea elementalísima, pero orgánica y completa,
que facilitara desde el primer día la traducción y evitara la presentación de paradigmas
abstractos y carentes de aplicación inmediata. La morfología regular y una sintaxis
en embrión, reducida a las reglas esenciales de la oración simple, nos bastaban para
lanzar al alumno a la traducción de lecturas graduadas sobre asuntos de la historia
hispanorromana o fábulas prosificadas e incluso para iniciarle en los secretos de la
composición latina.

La presente gramática va dirigida en cambio a alumnos que posean ya un conocimiento
rudimentario de la lengua latina o cuya edad haga innecesaria una dosificación demasiado
lenta. Puede usarse, por tanto, a partir del segundo curso y contiene una morfología
lo bastante completa para que el estudiante pueda utilizarla en todo el curso del
actual bachillerato.

Hemos seguido el criterio del Cuestionario oficial, con el que está de acuerdo nuestra
experiencia, de prescindir de toda explicación de lingüística histórica. Creemos firmemente
que, si bien pueden en ocasiones ser oportunas explicaciones de este género, deben quedar
siempre a la libre iniciativa del profesor, quien sabrá no sólo dosificarlas, sino distinguir
qué parte de la clase está capacitada para asimilarlas. En el texto, en cambio, no sería
sino una ineficaz complicación añadida a un estudio ya en sí nada fácil.

Por otra parte sostenemos que el estudio de las reglas sintácticas debe iniciarse desde
los primeros pasos. Para ello, nada mejor que prescindir de una división artificial
entre Morfología y Sintaxis, intercalando las reglas de ésta a medida que el estudio
de las formas ofrece ocasión para ello. Así lo hemos hecho en este libro y en los
capítulos finales hemos completado y sistematizado de un modo rudimentario los
conocimientos previamente adquiridos. De esta forma el alumno, en posesión de las
categorías sintácticas fundamentales y de los más importantes usos de la lengua, estará
en disposición de adentrarse, en los cursos superiores, en el estudio de una Sintaxis completa.

Otro de nuestros principios es que cada lección vaya acompañada de los correspondientes
ejercicios. No basta una Antología; conviene que cada regla esté ejemplificada por un
número suficiente de ejercicios, tanto de traducción al castellano, como de versión
al latín. Para no aumentar exageradamente el volumen y facilitar mejor la gradación,
hemos impreso los ejercicios apartefootnote:[_Ejercicios Latinos_. Primer grado. Barcelona. 1943. Bosch, casa editorial.],
divididos en lecciones y con referencia
a los párrafos de la Gramática. Finalmente hemos aplicado una especial atención a
la presentación tipográfica, cuidando de que ésta fuera clara y variada. Los párrafos
en letra pequeña, pueden reservarse, según criterio del profesor, para cursos más
avanzados o discípulos más aventajados.

EL AUTOR

Barcelona, abril 1943.
