== Generalidades

[paragrafo]#*§1 LA LENGUA LATINA*#.–
El Latín fue primitivamente la lengua hablada en el Lacio,
pequeña comarca de la Italia central, a la orilla izquierda del Tíber. Esta lengua,
junto con otros dialectos como el osco y el umbro, formaba la rama itálica de la
gran familia de lenguas indoeuropeas que se extendió por toda Europa y parte del
Asia, y cuyos otros principales representantes son el sánscrito, el iranio, el
griego, el eslavo, el báltico, el germánico y el celta.

Las armas romanas hicieron la fortuna del latín. La ciudad de Roma, que empezó siendo
hacia el siglo VIII antes de Jesucristo un pequeño pueblo de agricultores, se convirtió
pronto en capital del Lacio y extendió después su autoridad sobre toda la península italiana.
Las guerras con Cartago le dieron el dominio sobre el Mediterráneo occidental, España, Norte
de África y costas meridionales de Francia. Los países de la parte oriental del Mediterráneo
no tardaron en caer bajo la influencia del nuevo poder y pronto se convirtieron en provincial romanas.

En el siglo I antes de J.C. Roma, convertida en cabeza de un Imperio Mundial, se dio
las instituciones adecuadas a su nueva función. El régimen imperial fue establecido
en sus líneas esenciales por Julio César y su sucesor Augusto. En aquel tiempo el
Imperio se extendía sobre lo que hoy son lo países siguientes: Italia, España y Portugal,
Francia, Gran Bretaña, Bélgica, provincias alemanas del Rin, Bohemia, Suiza, países
danubianos de la Europa Central, península balcánica, Asía Menor, Siria, Palestina,
Egipto y costa mediterránea del África.

La lengua oficial de este Imperio era el latín, que paulatinamente fue suplantando
las viejas lenguas indígenas; pero en los países orientales del Mediterráneo dominaba
el griego, que por su alta significación como lengua de cultura, pudo resistir
ventajosamente a la expansión del idioma romano.

En estas regiones el latín fue evolucionando lentamente y adaptándose a las particularidades
lingüísticas de cada una de ellas. Al romperse la unidad del Imperio ante el empuje
de los pueblos nórdicos, desapareció el principal sostén de la unidad lingüística
y se hizo posible la aparición de un sinnúmero de dialectos que con el tiempo habían
de convertirse en las lenguas romances modernas.

Nuestra lengua española no es más que la lengua imperial de Roma modificada por
el genio particular de nuestro pueblo y por las diversas influencias que desde
entonces se han ejercido en nuestro país.

Estudiar el latín es, pues, a la vez estudiar el idioma de nuestros antepasados,
la fuente de nuestra lengua actual, y el lazo de parentesco que la une con las
demás lenguas modernas del Occidente de Europa, especialmente el portugués, el francés,
el italiano, y en cierta medida, el inglés. Es además estudiar el vehículo de la
cultura europea moderna y el medio de que se ha valido durante siglos la Iglesia
Romana y se vale todavía para ejercer su autoridad y definir su doctrina.

[paragrafo]#*§2 EL ALFABETO LATINO*#.–
El alfabeto latino, derivado de un alfabeto griego, es, esencialmente, el mismo
que el español. Hacia el siglo I de nuestra era constaba de los 23 signos siguientes:

 A B C D E F G H I K L M N O P Q R S T V X Y Z
 a b c d e f g h i k l m n o p q r s t v x y z

En muchas ediciones modernas de textos latinos se usa además la j para designar
el sonido de la i consonante; ejemplos: juvenis, jam. También suelen distiguirse
los dos valores de la u, escribiendo v cuando es consonante, como en video y u
cuando vocal, como en unda. Nosostros mantendremos el signo i para los dos sonidos,
vocálico y consonante, pero distinguiremos, para evitar confusiones, entre u vocal
y v consonante.

[paragrafo]#*§3 VOCALES*#.–
Las vocales latinas son cinco, como en castellano:

 a e i o u

Su pronunciación es sensiblemente la misma que en nuestra lengua. Las vocales i,
u, ante otra vocal y formando sílaba con ella, tienen valor consonantico. Cuando
u sea consonante, la escribiremos v.

[paragrafo]#*§4 DIPTONGOS*#.–
En latín se encuentran los diptongos siguientes: ae, au, oe y menos frecuentes,
ei, eu, ui.

Ae, oe se escriben a veces æ, œ y en latín vulgar y tardío se pronunciaban e;
ejemplos: rosae (rose), proelium (prelium). Para mantener el uso clásico hay que
pronunciar muy rápidamente la e, con el objeto de formar una sola sílaba.

*§5 CONSONANTES*.–
Las consonantes latinas se clasifican del modo siguiente:

.Consonantes
[options="header", cols="^,^,^,^,^"]
|===
2+| | Labiales | Dentales | Guturales
.2+.^| Oclusivas | Sordas  | p | t | c, k, q
               | Sonoras | b | d | g
2+| Nasales | m | n |
2+| Fricativas | f | s, z |
2+| Líquedas | | l, r |
|===

h que primitivamente marcaba una aspiración, perdió pronto, como en castellano,
todo valor fonético.

x es una letra doble que puede representar cs o gs.

*§6 PRONUNCIACIÓN DE LAS CONSONANTES*.–
Se pronuncian en general como las castellanas, pero si se quiere mantener, en lo
posible, la pronunciación clásica, deben tenerse en cuenta las particularidades siguientes:

. c, g ante e, i se pronuncian del mismo modo que ante a, o, u; ejemplos:
Cícero (pr. quíquero), genus (pr. guenus), agito (pr. águito).

. ll se pronuncia como dos eles, ejemplos: ille (pr. il-le), vallum (pr. val-lum).

. Después de q y g la u se pronuncia siempre, con un sonido rápido; ejemplos:
quartus (pr. quartus), queror, (pr. cuéror), sanguis (pr. sanguis).

. ch se pronuncia como c sencilla; ejemplos: pulcher (pr. pulcher), machina (pr. máquina).

. z equivale al sonido ds; ejemplos: gaza (pr. gadsa), Zama (pr. dsama).

*§7 CANTIDAD*.–

*§8 ACENTO*.–
Para el acento prosódico latino, valen las siguients reglas:

[paragrafo]#§9#

[paragrafo]#§10#

[paragrafo]#§11#
