= Elementos de Sintaxis

== La Oración y sus partes

=== Concordancia

*§259/§249 Concordancia del verbo con el sujeto*
El verbo concuerda con su sujeto en número y persona,
siguiendo las mismass reglas que el castellano:

[NOTE]
====
*Hostis fugit*, _el enemigo huye_. +
*Cicero et Terentia valent*, _Cicerón y Terencia están bien_. +
*Si tu et Tullia valetis, ego et Cicero valemus*,
_si tú y Tulia estáis bien, yo y Cicerón estamos bien_.
====

Pero si hay más de un sujeto, el verbo puede concertar también con el
más próximo:

NOTE: *Venit pater et mater*, _vino el padre y la madre_.

*§250 Concordancia del sujeto y el predicado nominal*

a. Un solo sujeto. Si el predicado nominal es una adjetivo, concierta
con el sujeto en género, número y caso:
+
[NOTE]
====
*Verae amicitiae _sempiternae_ sunt*, _las verdaderas amistades son eternas_.
====
+
Si el predicado es un substantivo, concierta con el sujeto en caso,
y si es posible, en género y número.
+
[NOTE]
====
*Nos _causa_ belli sumus*, _somos nosotros la causa de la guerra_. +
*Sol est _rex_ caeli, luna est _reguina_ siderum*,
_el sol es el rey del cielo, la luna es la reina de los astros_.
====

b. Con más de un sujeto. Si hay varios sujetos, y éstos son del mismo
género, el predicado nominal se pone en plural y en el mismo género que
los sujetos:
+
[NOTE]
====
*Pater ete filius sunt _boni_*, _el padre y el hijo son bueno_.
====
+
Si son de género distinto y son nombres de seres animados, el
predicado nominal va en masculino plural; si son nombres de cosas,
el predicado suele ponerse en plural neutro:
+
[NOTE]
====
*Pater et mater sunt _boni_*, _el padre y la madres son buenos_. +
*Virtus et vitium sunt _contraria_*, _la virtud y el vicio son contrarios_.
====
+
A veces, en lugar de concertar con todos los sujetos, el predicado
nominal concierta sólo con el más próximo:
+
NOTE: *_Bonus_ est pater et mater*, _el padre y la madre son buenos_.
+
TIP: _bueno es el padre y la madre_ (REVISAR)

*§251 Concordancia entre substantivo y adjetivo*.
El adjetivo atributivo concierta en género, número y caso con el substantivo
calificado o determinado por él:

====
*Amicus _certus_ in re _incerta_ cernitur*,
_el amigo seguro se conoce en una situación insegura_
====

Si el adjetivo califica a varios substantivos, concierta con el más
próximo (o a veces se repite con cada uno de ellos):

====
*_Omnes_ aedes et templa*, _todas las casas y templos_
(también: omnes aedes omniaque templa).
====

*§252 Concordancia de la aposición*.
La aposición concierta con el substantivo a que se refiere en caso y,
si es posible, también en género y número:

====
*Servius Tullius _rex_*, _el rey Servio Tulio_. +
*Athenae, _caput_ Graeciae, antiqua est urbs*;
_Atenas, capital de Grecia, es una ciudad antigua_.
====

[small]#Nótese que, en castellano, cuando un nombre propio de ciudad está en
aposición con el nombre común correspondiente, lleva la preposición de:
_La ciudad de Roma_, *urbs Roma*.#

[NOTE]
====
Nótese que, en castellano, cuando un nombre propio de ciudad está en
aposición con el nombre común correspondiente, lleva la preposición de
: _La ciudad de Roma_, *urbs Roma*.
====

*§253 CONCORDANCIA DEL RELATIVO CON SU ANTECEDENTE*.
El relativo concierta con su antecedente en género y número.
En cuanto al caso, adopta el que le corresponde según la función
que desempeña en la oración (véase §315).

====
*Duas _vias_ occupavit, _quibus_ hostes exierant*;
_ocupó los dos caminos, por los que habían salido los enemigos_.
====

====
*Duas _vias_ occupavit, _quibus_ hostes exierant* ->
_ocupó los dos caminos, por los que habían salido los enemigos_.
====
