== Primera Declinación

=== (Tema en -a-)
=== Genitivo: -ae

*§16*
Esta declinación comprende sustantivos y adjetivos femeninos y algunos
sustantivos masculinos. El nominativo singular termina en *-a*.

.Tabla de Desinencias
[cols="^,^,^",options="header"]
|===
| | Singular | Plural
s| NOMINATIVO .2+.^| -ă .2+.^| -ae
s| VOCATIVO
s| ACUSATIVO | -am | -ās
s| GENITIVO .2+.^| -ae | -ārum
s| DATIVO .2+.^| -īs
s| ABLATIVO | -ā
|===

Paradigmas:

. Substantivo: *rosa*, _la rosa_.
. Adjetivo: *bona*, _buena:_

.Tabla de desinencias paradigma de los substantivos
[cols="^,^,^,^,^",options="header"]
|===
| 2+| Singular 2+| Plural
s| NOMINATIVO | ros**ă** -> _la rosa_ | bon**ă** -> _buena_ | ros**ae** -> _las rosas_ | bon**ae** -> _buenas_
s| VOCATIVO | ros**ă** -> _(oh) rosa_ | bon**ă**  | ros**ae** -> _(oh) rosas_ | bon**ae**
s| ACUSATIVO | ros**am** -> (a) la rosa | bon**am** | ros**ās** -> (a) las rosas | bon**ās**
s| GENITIVO | ros**ae** -> de la rosa | bon**ae** | ros**ārum** -> de las rosas | bon**ārum**
s| DATIVO | ros**ae** -> a, para la rosa | bon**ae** | ras**īs** -> a, para las rosas  | bon**īs**
s| ABLATIVO | ros**ā** -> con la rosa | bon**ā** | ros**īs** -> con las rosas | bon**īs**
|===

*§17 GÉNERO*.-
Los sustantivos de esta declinación son en general femeninos, excepto los nombres
de varón y oficio de varón, y la mayor parte de los ríos, que son masculinos.
Ejs.: *nauta*, _el marinero_, *scriba*, _el escriba_, *agricola*, _el campesino_,
*Cotta* (nombre propio), _Cota_, *Sequana*, _el Sena_, *Mosella*, _el Mosela_.

*§18 PARTICULARIDADES*.-

. Los nombres *dea*, _diosa_, *filia*, _hija_, *liberta*, _liberta_, cuando
aparecen al lado de sus correrspondientes masculinos
*deus*, _dios_, *filius*, _hijo_, *libertus*, _liberto_, presentan en el
Dat. y Abl. del plural una desinencia en *-ābus*:
+
[NOTE]
====
filiis et fili**abus** -> _a los hijos y las hijas_.

Usados separadamente, tienen las desinencia regular
en *-is*: *deis*, *filiis*, *libertis*.
====

. Los nombres compuestos en *-cola* y *-gena* presentan a veces, aunque sólo
en poesía, un Genitivo plural en *-um* en vez del regular en *-arum*:
+
[NOTE]
====
*agricola*, _campesino_, Gen. pl. agricol**arum** o agricol**um**.

*Graiugena*, _griego de nacimiento_, Gen. pl. Graiugen**arum** o Graiugen**um**.
====

. En los términos jurídicos pater familias, mater familias,
_padre de familia_, _madre de familia_, en lugar de pater familiae, mater familiae,
encontramos un resto de una antigua desinencia del Gen. sing. en *-as*.

. Nótese el cambio de sentido de las siguientes palabras al pasar del
singular al plural:
+
[NOTE]
====
*copia*, _abundancia_	-> *copiae*, _tropas_

*littera*, _letra_ -> *litterae*, _carta_, _literautura_
====

. Las palabras siguientes sólo se usan en plural:
+
[NOTE]
====
*nuptiae*, _bodas_ +
*reliquiae*, _restos_ +
*tenebrae*, _tinieblas_ +
*angustiae*, _desfiladero_ +
*divitiae*, _riquezas_ +
*indutiae*, _tregua_
====
y algunos nombres de ciudad: *Athenae*, _Athenas_, *Syracusae*, _Siracusa_.

*§19 EL LOCATIVO*.-
Los nombres de ciudad, en singular, de la primera declinación,
como *Roma*, *Malacca*, _Málaga_, *Caesaraugusta*, _Zaragoza_, conservan un antiguo
caso, llamado _Locativo_, que sirve para indicar el lugar en dónde algo
ocurre o alguien se encuentra. Su desinencia es *-ae*.

[NOTE]
====
*Roma*, _en Roma_ +
*Malaccae*, _en Málaga_ +
*Caesaraugustae*, _en Zaragoza_
====

Los nombres de ciudad que tienen forma de plural, suplen el Locativo
por el Ablativo:

[NOTE]
====
*Athenis*, _en Atenas_ +
*Syracusis*, _en Siracusa_
====

*§20 USO DE LOS CASOS*.-

. El _Nominativo_ es el caso del _sujeto_ y del _predicado nominal_.
+
_Sujeto_ es la palabra que designa al ser de que se afirma a niega algo.
Responde en castellano a las preguntas _¿quién?_ o _¿qué?_:
+
[NOTE]
====
_La niña ríe_: *puella ridet* +
_Los campesinos aran_: *agricolae arant* +

¿Quién ríe? _La niña_ +
¿Quién ara? _Los campesinos_
====
+
En las oraciones sustantivas o de verbo _ser_, se llama _predicado nominal_ (o atributo)
el adjetivo o sustantivo que expresa la cualidad afirmada del sujeto:
+
[NOTE]
====
_La rosa es bella_:  *rosa est pulchra* +
_Las niñas son perezosas_:  *puellae sunt pigrae*
====

. El _Vocativo_ es el caso en que se pone el nombre de la persona o cosa
a la que  dirigimos la palabra. Puede llevar la interjección  "o"  (castellano oh),
suele ir entre comas y equivale a una exclamación aparte del resto de la frase:
+
[NOTE]
====
¡Oh rosa, cuán bella eres!: O rosa, quam pulchra es!
Reina, sé clemente: Regina, esto clemens.
====

. El _Acusativo_ es el caso del _complemento directo_ de los verbos transitivos.
+
_Complemento directo_ es la palabra que indica la persona o cosa
sobre la que recae directamente la acción expresada por el verbo. Responde
en castellano a las preguntas *¿a quién?* o *¿qué?*:
+
[NOTE]
====
_la esclava ama a la niña_: *serva amat puellam* +
_el labrador recorre las selvas_: *agrícola peragrat silvas*

¿A quién ama la esclava? a la niña +
¿Qué recorre el labrador? las selvas
====

. El _Dativo_ es el caso del _complemento indirecto_.
+
El _complemento indirecto_ indica la persona en cuyo interés se realiza
la acción expresada por el verbo. En castellano lleva las preposiciones
_a_ o _para_ y responde a las preguntas *¿a quién?* o *¿para quién?*:
+
[NOTE]
====
_la esclava prepara la cena para la señora_: *Serva parat cenam dominae* +
_el campesino da rosas a las niñas_: *Agrícola dat rosas puellis*

¿Para quién prepara la cena? *Para la señora* +
¿A quién da rosas? *A las niñas*
====

. El _Ablativo_ es el caso del _complemento circunstancial_.
+
_Complemento circunstancial_ es la palabra que modifica la significación del
verbo expresando circunstancias de lugar, tiempo, instrumento, modo,
causa, etc. En castellano puede ir acompañado de todas las preposiciones y
responde a las preguntas _¿dónde?_, _¿cuándo?_, _¿con qué?_, _¿cómo?_,
_¿por qué?_, etc.:
+
[NOTE]
====
_la sed se aplaca con agua_: *Sitis aqua extinguitur* +
_en las selvas hay muchas fieras_: *In silvis sunt multae bestiae* +

¿Con qué se aplaca la sed? _Con el agua_ +
¿Dónde están las fieras? _En las selvas_
====

. El _Genitivo_ es el caso del _complemento determinativo del nombre_.
Lleva en castellano la preposición _de_:
+
[NOTE]
====
_me gustan las plumas del águila_: *Amo pennas aquilae* +
_el perfume de las rosas_: *Odor rosarum* +

¿Qué plumas?  _Las del águila_ +
¿Qué perfume?  _El de las rosas_
====
