== El Adjetivo

*§55* Los adjetivos latinos se declinan como los substantivos y se dividen en
dos grandes clases según la declinación que siguen:

. Los que se declinan según la 1ra y la 2da declinaciones.
. Los que se declinan según la 3ra declinación.

La primera clase comprende los llamados adjetivos de _tres_ terminaciones;
la segunda, los de _dos_ y de _una_ terminación.

*§56 ADJETIVOS DE TRES TERMINACIONES*.
Estos adjetivos poseen tres formas:
una en *-us* o en *-er*, para el masculino, perteneciente a la 2da declinación;
una en *-a*, para el femenino, perteneciente a la 1ra declinación; y una en *-um*,
para el neutro, perteneciente a la 2da declinación neutra.

[NOTE]
====
Paradigmas:

. banus, bona, bonum, _bueno_
. pulcher, pulchra, pulchrum, _hermoso_
. tener, tenera, tenerum, _tierno_
====

.Adjetivos terminados en *us*, *a* y *um*
[cols="^,^,^,^,^,^,^"]
|===
.2+| 3+h| Singular 3+h| Plural
| Masculino | Femenino | Neutro | Masculino | Femenino | Neutro
s| NOMINATIVO | bon**ŭs** | bon**ă** | bon**um** | bon**ī** | bon**ae** | bon**ă**
s| VOCATIVO | bon**ĕ** | bon**ă**  | bon**um** | bon**ī** | bon**ae** | bon**ă**
s| ACUSATIVO | bon**um** | bon**am** | bon**um** | bon**ōs** | bon**ās** | bon**ă**
s| GENITIVO | bon**ī** | bon**ae** | bon**ī** | bon**ōrum** | bon**ārum** | bon**ă**
s| DATIVO | bon**ō** | bon**ae** | bon**ō** 3+| bon**ī**
s| ABLATIVO | bon**ō** | bon**ā** | bon**ō** 3+| bon**ī**
|===

*§57. Adjetivos de dos terminaciones*. -- Siguen la
3ra declinación y tienen dos terminaciones, una en *-is* para
el masc. y fem. y una en *-e* para el neutro. Se declinan como
los temas en *-i-* y hacen el Abl. sing. en *-i*.

.Paradigmas: *fortis*, *e*, _valeroso_.
[cols="^,^,^,^,^,^,^"]
[cols="^,^,^,^,^",]
|===
.2+| 2+h| Singular 2+h| Plural
h| Masc. Fem. h| Netro h| Masc. Fem. h| Neutro
s| NOMINATIVO .2+^.^| fortis .3+^.^| fortĕ .3+^.^| fortēs .3+^.^| fortiă
s| VOCATIVO
s| ACUSATIVO | fortem
s| GENITIVO 2+| fortĭs 2+| fortium
s| DATIVO 2+| fortī 2+| fortĭbus
s| ABLATIVO 2+| fortī 2+| fortībus
|===

Algunos adjetivos de este tipo presentan en el Nom. y
Voc. sing. tres formas: una en *-er* para el masc. una en *-is*
para el fem. y otra en *-e* para el neutro. Ejemplo: *acer*,
*acris*, *acre*, _agudo_.

*§*. --
