== El Adjetivo

*§55* Los adjetivos latinos se declinan como los substantivos y se dividen en
dos grandes clases según la declinación que siguen:

. Los que se declinan según la 1ra y la 2da declinaciones.
. Los que se declinan según la 3ra declinación.

La primera clase comprende los llamados adjetivos de _tres_ terminaciones;
la segunda, los de _dos_ y de _una_ terminación.

*§56 ADJETIVOS DE TRES TERMINACIONES*.
Estos adjetivos poseen tres formas:
una en *-us* o en *-er*, para el masculino, perteneciente a la 2da declinación;
una en *-a*, para el femenino, perteneciente a la 1ra declinación; y una en *-um*,
para el neutro, perteneciente a la 2da declinación neutra.

[NOTE]
====
Paradigmas:

. banus, bona, bonum, _bueno_
. pulcher, pulchra, pulchrum, _hermoso_
. tener, tenera, tenerum, _tierno_
====

.Adjetivos terminados en *us*, *a* y *um*
[cols="^,^,^,^,^,^,^"]
|===
.2+| 3+h| Singular 3+h| Plural
| Masculino | Femenino | Neutro | Masculino | Femenino | Neutro
s| NOMINATIVO | bon**ŭs** | bon**ă** | bon**um** | bon**ī** | bon**ae** | bon**ă**
s| VOCATIVO | bon**ĕ** | bon**ă**  | bon**um** | bon**ī** | bon**ae** | bon**ă**
s| ACUSATIVO | bon**um** | bon**am** | bon**um** | bon**ōs** | bon**ās** | bon**ă**
s| GENITIVO | bon**ī** | bon**ae** | bon**ī** | bon**ōrum** | bon**ārum** | bon**ă**
s| DATIVO | bon**ō** | bon**ae** | bon**ō** 3+| bon**ī**
s| ABLATIVO | bon**ō** | bon**ā** | bon**ō** 3+| bon**ī**
|===

*§57. Adjetivos de dos terminaciones*. -- Siguen la
3ra declinación y tienen dos terminaciones, una en *-is* para
el masc. y fem. y una en *-e* para el neutro. Se declinan como
los temas en *-i-* y hacen el Abl. sing. en *-i*.

.Paradigmas: *fortis*, *e*, _valeroso_.
[cols="^,^,^,^,^,^,^"]
[cols="^,^,^,^,^",]
|===
.2+| 2+h| Singular 2+h| Plural
h| Masc. Fem. h| Netro h| Masc. Fem. h| Neutro
s| NOMINATIVO .2+^.^| fortis .3+^.^| fortĕ .3+^.^| fortēs .3+^.^| fortiă
s| VOCATIVO
s| ACUSATIVO | fortem
s| GENITIVO 2+| fortĭs 2+| fortium
s| DATIVO 2+| fortī 2+| fortĭbus
s| ABLATIVO 2+| fortī 2+| fortībus
|===

Algunos adjetivos de este tipo presentan en el Nom. y
Voc. sing. tres formas: una en *-er* para el masc. una en *-is*
para el fem. y otra en *-e* para el neutro. Ejemplo: *acer*,
*acris*, *acre*, _agudo_.

*§*. --

=== Grados de significación de los adjetivos

*§63*. Una cualidad puede ser poseída en grado mayor o
menor. Y comparando dos o más objetos dotados de la misma
cualidad podemos notar diferencias entre ellos. Así decimos:

_los Alpes son más altos que los Pirineas;_

o, refiriendonos a todos los objetos de una misma especie:

_el Himalaya es la más alta de las cordilleras._

También podemos decir:

_esta rosa es bellísima_, +
_el agua de esta fuente es muy fresca_,

con lo cual afirmamos que un objeto posee una cualidad en
muy alto grado.

Por lo tanto, podemos distinguir en el adjetivo tres grados
de significación:

*Positivo*, cuado el adjetivo se limita a calificar al
substantivo: _un árbol alto_.

*Comparativo*, cuando se comparan dos objetos que
poseen la misma cualidad y se establecen diferencias entre
ellos:

_este pino es más alto que aquél_ (conparativo de superioridad)

_este pino es menos alto que aquél_ (comparativo de inferiordad)

_este pino es tan alto como aquél_ (comparativo de igualdad)

*Superlativo*, cuando se dice que un objeto que tiene
una cualidad en muy alto grado (superlativo absoluto),
o en grado superior a todos los demás de su especie
(superlativo relativo):

_un pino altísimo, o muy alto_

_el más alto de los pinos_.

*§64*. Formación del Comparativo Latino. -- El latín
forma el comparativo de los adjetivos substituyendo la desinencia
del Genit. sing. por las terminaciones *-ior*, (masc. y fem.),
*-ius* (neutro). Así pues, al ponerse en grado comparativo,
todos los adjetivos se convierten en adjetivos de dos
terminaciones; se declinan según la 3ra decl. y su Genit. sing.
es en *-iōris*.

.{zwsp}
====
[options="header", cols=","]
|===
^| Positivo ^| Comparativo

|*altus*, _alto_, Gen. *alt-i* +
*fortis*, _valeroso_, Gen. *fort-is* +
*prudens*, _prudente_, Gen. *pru-dent-is*

|*alt-ior, alt-ius*, _más alto_, Gen. *altiōris* +
*fort-ior, fort-ius*, _más valeroso_, Gen. *fortiōris* +
*prudent-ior, prudent-ius*, _más prudente_, Gen. *prudentiōris*
|===
====

Esta formación es la del comparativo de superioridad.
Los de igualdad e inferioridad se forman en latín, como en
castellano, por medio de adverbios:

*tam altus*, _tan alto_; *tam fortis*, _tan valeroso_; *tam prudens*, _tan prudente_

*minus altus*, _menos alto_; *minus fortis*, _menos valeroso_;
*minus pridens*, _menos prudente_;

*§65*. Declinación del Comparativo. -- Sigue totalmente
la declinación de los temas en consonante de la 3ra declinación
(Abl. sing. *-ĕ*; Gen. pl. *-um*; Nom. Voc. Ac. pl. n. *-ă*):

.{zwsp}
[cols="^,^,^,^,^,^,^"]
[cols="^,^,^,^,^",]
|===
.2+| 2+h| Singular 2+h| Plural
h| Masc. Fem. h| Netro h| Masc. Fem. h| Neutro
s| NOMINATIVO .2+^.^| altior .3+^.^| altius .3+^.^| altiōrēs .3+^.^| altiōră
s| VOCATIVO
s| ACUSATIVO | altiorem
s| GENITIVO 2+| altiōrĭs 2+| altiōrum
s| DATIVO 2+| altiōri 2.2+^.^| altiōrĭbus
s| ABLATIVO 2+| altiōrĕ
|===

*§66*. Formaciones Particulares del Comparativo. --
Los adjetivos terminados en *-dĭcus*, *-fĭcus* y *-vŏlus* forman
su comparativo en *-entior*:

*maledĭcus*, _maldiciente_, comp. *maledicentior*, *ius* +
*benefĭcus*, _benéfico_, comp. *beneficentior*, *ius* +
*benevŏlus*, _benévolo_, comp. *benevolentior*, *ius*

*Maledicentior* y *benevolentior* son en realidad comparativos
de *maledicens* y *benevolens*; de aquí su forma.

*§67*. Régimen del Comparativo. -- Para traducir la partícula
_que_, que en castellano antecede al segundo término
de una comparación, el latín utiliza dos procedimientos:

. Traduciendo la partícula _que_ por _quam_ y poniendo
el 2do término en el mismo caso que el primero:
+
.{zwsp}
====
_César fué más afortunado que Pompeyo_: *Caesar felicior
fuit quam Pompeius*.
====

. Poniendo el segundo término en Ablativo, sin traducir
la partícula _que_:
+
.{zwsp}
====
Caesar felicior fuit Pompeio.
====

*§68*. Valor Intensivo del Comparativo.-- A veces el comparativo
latino no se usa para comparar dos objetos sino con un sentido
equivalente al del castellano _bastante_ o _demasiado_ seguido de un
adjetivo:

.{zwsp}
====
*timidior est*: _es demasiado tímido_.
====
