== Apéndice I

=== Formación de las palabras

==== Derivación y composición

Para formar palabras nuevas de otras ya existentes son posibles
dos procedimientos: la _derivación_ y la _composición_.

_Palabra compuesta_ es aquella en cuya estructura distinguimos dos
elementos dotados, cada uno por si, de significación propia. Ejemplos:
*magnanimus* = *qui magnum animun habet*; *quadrupes* = *qui
quattuor pedes habet*.

_Palabra derivada_ es la formada de otra palabra simple mediante la
adición de un prefijo o sufijo que modifica su estructura y sentido, pero
que aislado no es ninguna palabra. Ejemplos: *audacia* de *audax*, *cursare* y
*cursitare* de *currere*.

==== Derivación

Las palabras derivadas pueden ser substantivos, adjetivos, verbos
y adverbios.

. *Substantivos Derivados*. Pueden derivarse o de un verbo, y
se llaman substantivos verbales, o de un substantivo o adjetivo, y se
llaman substantivos denominativos.
+
A. _Substantivos verbales_. Los substantivos derivados de un verbo
pueden serlo, o del tema de presente o del tema de supino.
+
.. Las terminaciones más corrientes de los substantivos derivados
del tema de presente, son:
+
*-or*: *amor*, _amor_, de *amare*, _amar_; *timor*, _temor_, de *timere*, _temer_.
(Indica actividad o estado).
+
*-men*: *flumen*, _rio_, de *fluo*, _fluir_; *agmen*, _ejército en marcha_, de *ago*,
_llevar_.
+
*-mentum*: *ornamentum*, _adorno_, de *orno*, _adornar_; *documentum*, _documento_,
de *docere*, _enseñar_.
+
*-bŭlum*: *pabulum*, _pasto_, de *pasco*, _apacentar_.
+
*-cŭlum*: *ferculum*, _litera_, de *fero*, _llevar_; *vehiculum*, _vehículo_, de *veho*,
_arrastrar_.
+
*-crum*: *aratrum*, _arado_, de _aro_, _arar_.  (Estos sufijos indican generalmente
el medio de realización y la realización misma de la acción).
+
*-a*: *scriba*, _escribano_, de *scribere*, _escribir_; *incola*, _habitante_, de *incolo*,
_habitar_.
+
*-ium*: *gaudium*, _gozo_; de *gaudere*, _alegrarse_.
+
.. Las terminaciones de los substantivos derivados del tema de
supino son:
+
*-tor* (masc.) y *-trix* (fem.): *victor*, _vencedor_ y *victrix*, _vencedora_, de
*vincere*, *victum*, _vencer_; *auctor*, _autor_, de *ago*, *actum*, hacer;
*fautor*, _favorecedor_ y *fautrix*, _favorecedora_, de *favere*, *fautum*,
_favorecer_ (indican el autor de la acción).
+
*-sor*: *tonsor*, _peluquero_, de *tondere*, *tonsum*, _esquilar_.
+
*-tio*: *actio*, _acción_, de *agere*, *actum*, _hacer_; *inventio*, _hallazago_, de *invenire*,
*inventum*, _hallar_.
+
*-sio*: *avulsio*, _desgaje_, de *avello*, *avulsum*, _arrancar_.
+
*-tus*: *motus*, _movimiento_, de *moverse*, *motum*, _mover_; *conventus*, _asamblea_,
de *convenio*, *conventum*, _reunirse_.
+
*-sus*: *cursus*, _carrera_, de *curro*, *cursum*, _correr_.
+
*-ŭra*: *pictura*, _pintura_, de *pingo*, *pictum*, _pintar_. (Estos sufijos forman
nombres expresando la acción).

Algunas desinencias, como *-monia*, *-ela*, se añaden a veces al tema
de presente y a veces al tema de supino. Ejemplos: tema de pres.:
*alimonia*, _limosna_, de *alere*, _alimentar_; *querimonia*, _queja_, de *queror*,
_quejarse_; *candela*, _cirio_, de *candere*, _brillar_. Tema de sup.: *parsimonia*,
_economía_, de *parcere*, *parsum*, _ahorrar_; *tutela*, _tutela_, de *tueri*,
*tutum*, _proteger_.

B. Substantivos denominativos.
  a. Los substantivos se derivan de otros substantivos por medio
  de los siguientes sufijos: +
  *-a*: dea, _diosa_, de *deus*; *magistra*, _maestra_, de *magister*.
