== La Conjunción

*§221* Las conjunciones son partículas que sirven para unir palabras entre si
en una oración, u araciones en una frase.

Se clasifican en _Coordinativas y Subordinativas_. Coordinativas son las que
unen dos palabras en una oración, o dos oraciones entre sí, sin modificar el modo
del verbo. Subordinativas son las que unen a la oración principal la oración
u oraciones que de ella dependen.

*§222* I. Conjunciones Coordinativas. a) Copulativas (indicando
unión), pueden ser _simples_ o _correlativas_. Las _simples_ son:

 et, ac, atque, -que: y
 neque, nec: y no, ni
 quoque: tambien
 etiam: aún, tambien
 ne quidem: ni

*§223* Observaciones.

. Ac, no se usa nunca ante vocal o h.
. Que, es una partícula enclítica que se une a la palabra como un sufijo.
Senatus populusque Romanus: _El Senado y el pueblo romano_ (abreviado: S.P.Q.R).
. Etiam se coloca ante la palabra que une: atiam ago, _también yo_; quoque se coloca
después de esta palabra: ego quoque, _yo también_.
. Et tiene, asimismo, valor de también. Veniet et mater eius: _Vendrá también su madre_.
. Cuando _y_ no se refiere a una palabra que no sea el verbo, se traduce por _et non_.
Brevis et non effusa oratio: _Un discurso breve y no prolijo_.
